---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: xbox
  name: xbox
  namespace: xbox
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: xbox
  type: LoadBalancer
---